[package]
name = "mpc-recovery"
version = "0.1.0"
edition = "2021"

# We have encountered issue with linking GMP on ARM macos machines. This is a temporary fix that
# replaces GMP implementation with num-bigint.
# [target.'cfg(macos)'.dependencies]
# curv = { package = "curv-kzen", version = "0.9", default-features = false, features = ["num-bigint"] }
# multi-party-eddsa = { git = "https://github.com/ZenGo-X/multi-party-eddsa.git", default-features = false }

# [target.'cfg(unix)'.dependencies]
# multi-party-eddsa = { git = "https://github.com/ZenGo-X/multi-party-eddsa.git" }

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.6"
clap = { version = "4.2", features = ["derive"] }
futures = "0.3"
hex = "0.4"
ractor = { version = "0.7", features = ["cluster"] }
ractor_cluster = "0.7"
actix-rt = "2.8"
threshold_crypto = "0.4.0"
rand = "0.7"
serde = "1"
serde_json = "1"
tokio = { version = "1.0", features = ["full"] }