[package]
name = "mpc-recovery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
actix = "0.13"
actix-rt = "2.8"
threshold_crypto = "0.4.0"
rand = "0.7"
