[package]
name = "mpc-recovery-gcp"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.8"
prost-types = "0.11.8"
tonic = "0.9.2"

[build-dependencies]
walkdir = "2.3.3"
tonic-build = "0.9.2"
